language: go

dist: bionic

os:
  - linux

env:
  global:
    - GO111MODULE=on

go:
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go fmt ./...
  - go vet ./...
  - golangci-lint run ./...
  - go test -trimpath --timeout=5m -failfast -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
